# Generated by Django 4.1.5 on 2023-01-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='The date of publication')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='The date of update')),
            ],
        ),
    ]
