# Generated by Django 4.1.5 on 2023-01-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='viewed',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
    ]
